### ISSUE TITLE
Substitute fmt with format

### ISSUE THREAD

**Issue by menkotoglou** [Tomperez98/pyrgo#18]
Hey,

Thank you very much for the project. I was wondering if fmt should be kept instead of `format`?

Every command is a full word, while we used an abbreviation for this, although it's not a really long word.

Thanks in advance!

**Comment by Tomperez98** [comment]
Hi! Thanks, first issue 😃.

I prefer `fmt` since it's used by `cargo`, which `pyrgo` inspires from and also the format command used by various tools like Terraform.

I would say it's a matter of getting used to it.

That said, if more people puch for it I'd change it.
